Добавляет разметку всех страниц
htmlacademy-adaptive/1737917-sedona-28 pull request #2
Opened 2023-04-09 20:42 UTC by Bezlpetr

2023-04-10 18:22 UTC, andreysgra requested changes
В целом разметка и именования классов выполнены правильно.

2023-04-10 18:22 UTC, andreysgra commented on source/catalog.html
> +  </div>
Ошибка именования класса по БЭМ. Блок `.main-header` не является родителем этого элемента:
![image](https://user-images.githubusercontent.com/17790771/230964980-1db66c8f-dc48-4244-a943-34db172ca026.png)
Вероятнее всего у вас просто ошибка расположения тега - он должен быть внутри `main`.

2023-04-10 18:22 UTC, andreysgra commented on source/catalog.html
> +      <video class="video__player" src="" preload="none"></video>
Ошибка валидации HTML. Атрибут `src` не должен быть пустым.

2023-04-10 18:22 UTC, andreysgra commented on source/form.html
> +  </div>
Здесь такая же ошибка, как и на странице каталога.

2023-04-10 18:22 UTC, andreysgra commented on source/index.html
> +  </div>
Здесь такая же ошибка, как и на странице каталога.

2023-04-11 03:36 UTC, Bezlpetr commented on source/catalog.html
> +  </div>
Я посчитал, что данный блок скорее относится к header, т.к. есть на всех страницах, поэтому перенес туда.

2023-04-11 03:44 UTC, Bezlpetr commented on source/catalog.html
> +      <video class="video__player" src="" preload="none"></video>
Мы пока не экспортировали изображения, поэтому все src пустые, предлагаю оставить так до этапа работы с изображениями.

2023-04-11 03:44 UTC, Bezlpetr commented on source/index.html
> +  </div>
Перенес в header

2023-04-11 18:01 UTC, andreysgra commented on source/catalog.html
> +      <video class="video__player" src="" preload="none"></video>
Это тег `video` и в `src` у него указывается путь к видеоролику.

2023-04-11 18:05 UTC, merged