Добавляет основную стилизацию всем страницам
htmlacademy-adaptive/1737917-sedona-28 pull request #3
Opened 2023-04-17 04:10 UTC by Bezlpetr

2023-04-17 07:21 UTC, andreysgra requested changes
1. На странице формы и каталога стоит добавить класс `main-nav--opened` в `nav`, чтобы меню было открыто.
2. Хотя мы ещё к заданию по сеткам не перешли, можно сделать одно дополнение - так как в этом макете контентная область имеет ограничение на десктопной версии, то весь контент, включая `main-header`, `.main-container`, `.main-footer` обернуть в `div`, который будет служить контейнером для контента. В макете контентная область отбрасывает тень (слой white back) и её можно применить к этому контейнеру.

2023-04-17 07:21 UTC, andreysgra commented on source/sass/blocks/control.scss
> +.control-input--checkbox + .control-mark {
Критерий [Б13](https://up.htmlacademy.ru/adaptive/28/criteries#b13) говорит о том, что стили для БЭМ блока и его производных (элементов и модификаторов) должны быть описаны в отдельном файле. Имя файла должно совпадать с названием класса блока.

Здесь мы видим, что файл называется .control.scss, а значит в нём может быть описан блок `.control`, элементы `..control__mark` и т.д., но описывать другие БЭМ блоки, такие как `.control-mark` нельзя.

Когда будете переделывать обратите внимания ещё на такой момент: у вас модификатор одно блока воздействует на другой блок `.control-input--radio:checked + .control-mark`. Это нарушает принцип независимости блоков. Нужно подумать над изменением пространства имён.

2023-04-17 07:21 UTC, andreysgra commented on source/sass/blocks/map.scss
> +.map-image {
[Б13](https://up.htmlacademy.ru/adaptive/28/criteries#b13)

2023-04-17 07:21 UTC, andreysgra commented on source/sass/blocks/page.scss
> +  font-family: "PT Sans", "Cuprum", sans-serif;
`Cuprum` из перечисления семейства шрифтов нужно убрать. Это не веб-безопасный шрифт.

2023-04-18 20:06 UTC, Bezlpetr commented on source/sass/blocks/control.scss
> +.control-input--checkbox + .control-mark {
Исправил

2023-04-18 20:08 UTC, Bezlpetr commented on source/sass/blocks/map.scss
> +.map-image {
Исправил

2023-04-18 20:09 UTC, Bezlpetr commented on source/sass/blocks/page.scss
> +  font-family: "PT Sans", "Cuprum", sans-serif;
Убрал

2023-04-19 17:54 UTC, merged